services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./cert:/cert
    ports:
      - 8808:80
      - 443:443